export const CHECK_BOOKING_REQUEST = "CHECK_BOOKING_REQUEST";
export const CHECK_BOOKING_SUCCESS = "CHECK_BOOKING_SUCCESS";
export const CHECK_BOOKING_RESET = "CHECK_BOOKING_RESET";
export const CHECK_BOOKING_FAIL = "CHECK_BOOKING_FAIL";

export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_RESET = "CREATE_BOOKING_RESET";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";

export const BOOKED_DATES_SUCCESS = "BOOKED_DATES_SUCCESS";
export const BOOKED_DATES_FAIL = "BOOKED_DATES_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
